namespace: gov-doc-rag

image:
  repository: "023268101038.dkr.ecr.us-east-1.amazonaws.com/gov-doc-rag-web"
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  host: "web.fedocx.online"
  path: /
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80},{"HTTPS":443}]'
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/group.name: gov-doc-rag
    alb.ingress.kubernetes.io/group.order: "2"
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:023268101038:certificate/5cba03e2-b1f6-420b-9ba3-3353f89469c1
    alb.ingress.kubernetes.io/ssl-redirect: "443"

resources:
  requests:
    cpu: "100m"
    memory: "128Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"

replicaCount: 2
