name: Deploy API
on:
  push:
    branches: [ main ]
    paths:
      - 'services/api/**'
      - '.github/workflows/deploy-api.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    env:
      AWS_REGION: us-east-1
      EKS_CLUSTER: gov-doc-rag-cluster
      ECR_REPO: 023268101038.dkr.ecr.us-east-1.amazonaws.com/gov-doc-rag-api
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::023268101038:role/GitHubOIDCDeployRole
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build & push image (multi-arch)
        uses: docker/build-push-action@v5
        with:
          context: ./services
          file: ./services/api/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.ECR_REPO }}:${{ env.IMAGE_TAG }}

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name "$EKS_CLUSTER" --region "$AWS_REGION"

      - name: Rollout new image
        run: |
          kubectl -n gov-doc-rag set image deploy/api api=${ECR_REPO}:${IMAGE_TAG}
          kubectl -n gov-doc-rag rollout status deploy/api
