name: Uptime

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Curl /health
        run: |
          set -euo pipefail
          URL="https://api.fedocx.online/health"
          for i in {1..3}; do
            CODE=$(curl -s -o /dev/null -w "%{http_code}" "$URL" || true)
            if [ "$CODE" = "200" ]; then
              exit 0
            fi
            sleep 10
          done
          echo "Health check failed"
          exit 1
